version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: web_translator
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_secret
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"